# Generated by Django 3.2.5 on 2023-01-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UerInfo',
            new_name='UserInfo',
        ),
    ]
